from django.conf.urls import patterns, url, include
from intelview import views


urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^login/$', 'django.contrib.auth.views.login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout'),
        url(r'^rec_login/$', views.rec_login, name='rec_login'),
        url(r'^eval_login/$', views.eval_login, name='eval_login'),
	url(r'^index/$', views.index, name='index'),
	url(r'^rec_index/$', views.rec_index, name='rec_index'),
	url(r'^eval_index/$', views.eval_index, name='eval_index'),
	url(r'^createprofile/$', views.leaders, name='leaders'),
	url(r'^profile/$', views.businesses, name='businesses'),
	url(r'^background/$', views.organizations, name='organizations'),
	url(r'^demographic/$', views.help, name='help'),
        url(r'^essayquestions/$', views.help, name='help'),
        url(r'^demographic/$', views.help, name='help'),
        url(r'^recommenders/$', views.help, name='help'),
        url(r'^finalsubmission/$', views.help, name='help'),
        url(r'^help/$', views.help, name='help'),
        url(r'^staffview/$', views.help, name='help'),
        url(r'^forgot/$', views.help, name='help'),
        url(r'^forgot_confirmation/$', views.help, name='help'),
        url(r'^reset_password/$', views.help, name='help'),
        url(r'^rec_finalsubmission/$', views.help, name='help'),
        url(r'^eval_finalsubmission/$', views.help, name='help'),
        url(r'^received/$', views.help, name='help'),
        url(r'^rec_received/$', views.help, name='help'),
        url(r'^eval_received/$', views.help, name='help'),
        url(r'^evaluate/(?P<student_id>\d+)/$', views.organizationView, name='organizationView'),
        url(r'^recommend/(?P<student_id>\d+)/$', views.organizationView, name='organizationView'),
        url(r'^myrecommender/(?P<recommender_id>\d+)/$', views.organizationView, name='organizationView'),
	url(r'^view_recommendations/(?P<student_id>\d+)/$', views.organizationView, name='organizationView'),
	url(r'^view_evaluations/(?P<student_id>\d+)/$', views.leaderView, name='leaderView'),
)
