from django.conf.urls import patterns, url, include
from clfapplication import views


urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^login/$', 'django.contrib.auth.views.login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout'),
	url(r'^rec_login/$', views.rec_login, name='rec_login'),
	url(r'^eval_login/$', views.eval_login, name='eval_login'),
	url(r'^index/$', views.index, name='index'),
	url(r'^rec_index/$', views.rec_index, name='rec_index'),
	url(r'^eval_index/$', views.eval_index, name='eval_index'),
	url(r'^createprofile/$', views.createprofile, name='createprofile'),
	url(r'^profile/$', views.profile, name='profile'),
	url(r'^background/$', views.background, name='background'),
	url(r'^demographic/$', views.demographic, name='demographic'),
	url(r'^essayquestions/$', views.essayquestions, name='essayquestions'),
	url(r'^demographic/$', views.demographic, name='demographics'),
	url(r'^recommenders/$', views.recommenders, name='recommenders'),
	url(r'^finalsubmission/$', views.finalsubmission, name='finalsubmission'),
	url(r'^help/$', views.help, name='help'),
	url(r'^staffview/$', views.staffview, name='staffview'),
	url(r'^forgot/$', views.forgot, name='helforgotp'),
	url(r'^forgot_confirmation/$', views.forgot_confirmation, name='forgot_confirmation'),
	url(r'^reset_password/$', views.reset_password, name='reset_password'),
	url(r'^rec_finalsubmission/$', views.finalsubmission, name='finalsubmission'),
	url(r'^eval_finalsubmission/$', views.eval_finalsubmission, name='eval_finalsubmission'),
	url(r'^received/$', views.received, name='received'),
	url(r'^rec_received/$', views.rec_received, name='rec_received'),
	url(r'^eval_received/$', views.eval_received, name='eval_received'),
	url(r'^evaluate/(?P<student_id>\d+)/$', views.evaluate, name='evaluate'),
	url(r'^recommend/(?P<student_id>\d+)/$', views.recommend, name='recommend'),
	url(r'^myrecommender/(?P<recommender_id>\d+)/$', views.myrecommender, name='myrecommender'),
	url(r'^view_recommendations/(?P<student_id>\d+)/$', views.view_recommendations, name='view_recommendations'),
	url(r'^view_evaluations/(?P<student_id>\d+)/$', views.view_evaluations, name='view_evaluations'),
)
